version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: t-guide-bd
    environment:
      - POSTGRES_DB=t-guide
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: