version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: t-guide-db
    environment:
      - POSTGRES_DB=tguide
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8080/api/actuator/health | grep -q '\"status\":\"UP\"' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: